name: NuGet Generation

on:
  push:
    branches:
      - main
      - feature/inmem-outbox
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - uses: aarnott/nbgv@v0.4.0
        with:
          setAllVars: true

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
          include-prerelease: true
        #   source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        # env:
        #   NUGET_AUTH_TOKEN: ${{ secrets.PRACTICAL_CLEAN_DDD_TOKEN }}

      - name: Build solution and generate NuGet package
        run: |
          printenv
          echo "${{ env.PackageVersion}}"
          dotnet pack src/N8T.Core/N8T.Core.csproj -c Release --include-symbols --include-source -p:PackageVersion=$(PackageVersion) -o out
          dotnet pack src/N8T.Infrastructure/N8T.Infrastructure.csproj -c Release --include-symbols --include-source -p:PackageVersion=$(PackageVersion) -o out
          dotnet pack src/N8T.Infrastructure.EfCore/N8T.Infrastructure.EfCore.csproj -c Release --include-symbols --include-source -p:PackageVersion=$(PackageVersion) -o out
          dotnet pack src/N8T.Infrastructure.OTel/N8T.Infrastructure.OTel.csproj -c Release --include-symbols --include-source -p:PackageVersion=$(PackageVersion) -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push /home/runner/work/practical-clean-ddd/practical-clean-ddd/out/*.nupkg --api-key ${{ secrets.PRACTICAL_CLEAN_DDD_TOKEN }} --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PRACTICAL_CLEAN_DDD_TOKEN }}
